/**
 * Generic checkout URL used while a full gateway integration isn't wired
 * up. When set, `paymentService.createCheckout` redirects here regardless
 * of provider — swap for a real per-order checkout link generated by the
 * active provider's API.
 */
export const PAYMENT_URL = process.env.NEXT_PUBLIC_PAYMENT_URL ?? "";

export type PaymentProviderName = "asaas" | "stripe" | "mercadopago";

export interface CheckoutSession {
  url: string;
  providerReference?: string;
}

/** Minimal shape any payable record (order, legacy appointment, ...) needs. */
export interface Payable {
  id: string;
  amount_cents: number;
}

export interface PaymentProvider {
  name: PaymentProviderName;
  createCheckout(payable: Payable): Promise<CheckoutSession>;
}

/**
 * Asaas — Brazilian boleto/PIX/card gateway.
 * Docs: https://docs.asaas.com
 * Requires ASAAS_API_KEY (server-side only).
 */
class AsaasProvider implements PaymentProvider {
  name: PaymentProviderName = "asaas";

  async createCheckout(payable: Payable): Promise<CheckoutSession> {
    // TODO: POST /v3/payments to Asaas and return the generated invoiceUrl.
    if (!PAYMENT_URL) {
      throw new Error("PAYMENT_URL is not configured and Asaas integration is pending.");
    }
    return { url: PAYMENT_URL, providerReference: payable.id };
  }
}

/**
 * Stripe Checkout.
 * Docs: https://docs.stripe.com/checkout/quickstart
 * Requires STRIPE_SECRET_KEY (server-side only).
 */
class StripeProvider implements PaymentProvider {
  name: PaymentProviderName = "stripe";

  async createCheckout(payable: Payable): Promise<CheckoutSession> {
    // TODO: create a Checkout Session via stripe.checkout.sessions.create
    // and return session.url.
    if (!PAYMENT_URL) {
      throw new Error("PAYMENT_URL is not configured and Stripe integration is pending.");
    }
    return { url: PAYMENT_URL, providerReference: payable.id };
  }
}

/**
 * Mercado Pago Checkout Pro.
 * Docs: https://www.mercadopago.com.br/developers
 * Requires MERCADOPAGO_ACCESS_TOKEN (server-side only).
 */
class MercadoPagoProvider implements PaymentProvider {
  name: PaymentProviderName = "mercadopago";

  async createCheckout(payable: Payable): Promise<CheckoutSession> {
    // TODO: POST /checkout/preferences and return init_point.
    if (!PAYMENT_URL) {
      throw new Error("PAYMENT_URL is not configured and Mercado Pago integration is pending.");
    }
    return { url: PAYMENT_URL, providerReference: payable.id };
  }
}

function resolveProvider(): PaymentProvider {
  const provider = process.env.NEXT_PUBLIC_PAYMENT_PROVIDER as PaymentProviderName | undefined;
  switch (provider) {
    case "stripe":
      return new StripeProvider();
    case "mercadopago":
      return new MercadoPagoProvider();
    case "asaas":
    default:
      return new AsaasProvider();
  }
}

export const paymentService = resolveProvider();
